# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_pict',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_articles',
        ),
        migrations.AddField(
            model_name='users',
            name='user_articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Articles'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_countries',
        ),
        migrations.AddField(
            model_name='users',
            name='user_countries',
            field=models.ManyToManyField(to='countries.Countries'),
        ),
    ]
