# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=20)),
                ('user_login', models.CharField(max_length=10)),
                ('user_password', models.CharField(max_length=20)),
                ('avatar', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_articles',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_countries',
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_pict',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='countrusers',
            name='user_articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Articles'),
        ),
        migrations.AddField(
            model_name='countrusers',
            name='user_countries',
            field=models.ManyToManyField(to='countries.Countries'),
        ),
        migrations.AddField(
            model_name='countrusers',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
