# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_pict',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
