# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20170121_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrusers',
            name='user_login',
        ),
        migrations.RemoveField(
            model_name='countrusers',
            name='user_mail',
        ),
        migrations.RemoveField(
            model_name='countrusers',
            name='user_password',
        ),
    ]
