# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20170107_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
