# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20170121_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrusers',
            name='avatar',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
