# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20170121_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Articles'),
        ),
    ]
