# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_countries_countries_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='countries_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
